branch-defaults:
  master:
    environment: mysite-dev
global:
  application_name: mysite
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-1
  profile: eb-cli
  sc: git
